version: "3.9"
services:
  backend-go:
    build: ./backend-go
    container_name: backend-go
    ports:
      - "8080:8080"
  worker-python:
    build: ./worker-python
    container_name: worker-python
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
    ports:
      - "4566:4566"