// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int32
	Username  string
	Email     string
	Pass      string
	CreatedAt pgtype.Timestamp
}

type UserSession struct {
	ID           int32
	UserID       int32
	SessionToken string
	CreatedAt    pgtype.Timestamp
	ExpiresAt    pgtype.Timestamp
}
